create table "public"."stories" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" character varying
);

alter table "public"."stories" enable row level security;

CREATE UNIQUE INDEX stories_pkey ON public.stories USING btree (id);

alter table "public"."stories" add constraint "stories_pkey" PRIMARY KEY using index "stories_pkey";